simulation:
  n_centers: 41
  n_days: 365
  n_outages: 10

delivery:
  base_time_seconds: 60  # 1 minute base time per parcel
  fixed_time_per_tour: 1800  # 30 minutes fixed time per tour
  tours_per_center_mean: 20
  tours_per_center_std: 3
  parcels_per_tour_mean: 200
  parcels_per_tour_std: 50
  min_parcels_per_tour: 50
  max_parcels_per_tour: 500

routing:
  dynamic_min_factor: 0.99  # Dynamic routing improves efficiency by 10-30%
  dynamic_max_factor: 0.99
  # Manual routing parameters for different parcel counts
  manual_routing_crossover_point: 200  # Parcels threshold where manual becomes worse
  # For small parcel counts (below crossover)
  manual_routing_small_min_factor: 0.6  # More efficient than dynamic for small counts
  manual_routing_small_max_factor: 0.9  # Approaches neutral at crossover
  # For large parcel counts (above crossover)
  manual_routing_large_min_factor: 0.9  # Starts neutral at crossover
  manual_routing_large_max_factor: 1.2  # Gets progressively worse for large counts
  # Legacy parameters (kept for backward compatibility)
  manual_min_factor: 0.7
  manual_max_factor: 0.9

analysis:
  noise_factor_mean: 1.0
  noise_factor_std: 0.1 